### ISSUE TITLE
Movement of dynamic body is jerky

### ISSUE THREAD

**Issue by bhushan6** [notrabs/use-ammojs#2]
I was creating first person prespective camera by mouting canera on topn of dynamic sphere but movement of sphere is little jerky even though the app runs at 60fps. I have created the small [demo](https://codesandbox.io/s/keyboard-controlled-sphere-using-ammojs-4ndlj?file=/src/index.js) on codesnadbox

**Comment by notrabs** [comment]
Thanks for the demo! It helped to find a sneaky little problem.

There is an optimization to skip the transform copies from the physics world to the three scene in case no physics update happened since the last transform copy. Turns out that wasn't implemented quite correctly 😅 

A [sandbox using the fixed version](https://codesandbox.io/s/keyboard-controlled-sphere-using-ammojs-forked-g4nc8?file=/src/index.js) is now quite a bit smoother.

However the motion is still not _completely_ jerk-free. In the long run it would probably look better if the physics run at a manually controlled constant rate, instead of relying on the bullet engine to quantize the variable performance.now() time back into fixed timesteps and skip updates every now and then to do so.
This would also be a good opportunity to get rid of the 60Hz default timestep and implement a more convenient "auto" behavior that matches the device refresh rate or some multiple of it.
